# Site settings
# --------------
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ .Site.Params.myvariable }}.
baseurl = "/" # The subpath of your site, e.g. / or /blog
languageCode = "en-us"
languageLang = "en"
defaultContentLanguage = "en"
title = "Helen Barff"
publishDir = "public"


# Categories and tags disabled for an easier start
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["taxonomy", "taxonomyTerm"]

# Enable this to have links relativized by Hugo
# E.g,  if your /post/first/ page contains a link
# to /about/, Hugo will rewrite the URL to ../../about/
relativeURLs = false

# Enable to have links open in new tab
hrefTargetBlank = false

# Site Params
# -------------
[params]
description = '''
'''
author = "Glenn Barr"

# Site Menus
# See the Hugo docs for usage in layouts
# https://gohugo.io/content-management/menus/
[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "biography"
    url = "/biography"
    weight = 2
[[menu.main]]
    name = "contact"
    url = "/contact"
    weight = 3
[[menu.main]]
    name = "instagram"
    url = "https://www.instagram.com/helenbarff/"
    weight = 4
[[menu.main]]
    name = "news"
    url = "/news"
    weight = 5

[blackfriday]
    extensions = ["hardLineBreak"]
